### PR TITLE
feat: set up SSL/TLS using ZeroSSL REST API

### PR DESCRIPTION
**Pull request by strophy**
This PR supersedes #102 by updating it to use the config system and config directory to serve files and store certs.

## Issue being fixed or feature implemented
10xcryptodev made great progress identifying and implementing a solution to get free SSL certs from ZeroSSL for IP addresses. This PR is intended to get his code working with the current dev branch of mn-bootstrap.

## What was done?
Refactored everything to work better with Listr2 and the ~/.mn config directory.

This does not yet implement a helper container to automatically run the certificate request when needed and monitor renewal. The renew command has also not been updated or tested. This work is left for a future PR.

Certs are not stored in separate folders for different configs, since the cert applies to the host, not the config. But it is still necessary to set `mn config:set platform.dapi.nginx.ssl.enable true` in the config to make it use the cert.

## How Has This Been Tested?
```
mn config:set <externalIp>
mn config:set platform.dapi.nginx.ssl.zerossl.apikey <apikey>
mn platform:dapi:ssl:obtain
```

Tested against ZeroSSL REST API, cert is successfully issued.
nginx seems to load certs properly, but I am unsure how to test the connection properly.

## Breaking Changes
It is now necessary to manually request a cert before starting the masternode.

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [ ] I have assigned this pull request to a milestone

### CODE REVIEW

**Comment by riongull** [comment]
Per @strophy on the Dash Devs Discord, The following steps should be sufficient from a clean install to get the cert. 

1. Obtain a ZeroSSL account (to get an API key)
2. Run the following commands:
```mn config:default evonet
mn config:set core.masternode.operator.privateKey <privkey>
mn config:set externalIp <ip>
mn config:set platform.dapi.nginx.ssl.zerossl.apikey <apikey>
mn platform:dapi:ssl:obtain
mn config:set platform.dapi.nginx.ssl.enable true
mn start```

**Comment by dashameter** [comment]
Details: [https://discordapp.com/channels/670271785974890526/713693491322159106/785810986116448299](https://discordapp.com/channels/670271785974890526/713693491322159106/785810986116448299)

Setup needs an additional step:

`sudo npm install --global http-server`

The challenge `https-server` port must be changed to [80](https://github.com/strophy/mn-bootstrap/blob/certs/src/ssl/zerossl/createZerosslCertificateTaskFactory.js#L59) and the `obtain` command be run at root:

`sudo mn platform:dapi:ssl:obtain`

(which means the configuration must be set as root / be present in `/root/.mn`)

A certificate draft is created and the cert issued as verified via zerossl.com.

Testing `https`:

```
curl 'https://[VPS]:3000/org.dash.platform.dapi.v0.Core/getStatus' \
  -H 'Connection: keep-alive' \
  -H 'Accept: application/grpc-web-text' \
  -H 'X-User-Agent: grpc-web-javascript/0.1' \
  -H 'X-Grpc-Web: 1' \
  -H 'Content-Type: application/grpc-web-text' \
  -H 'Accept-Language: en-US,en;q=0.9' \
  --data-binary 'AAAAAAA=' \
  --compressed \
```

Responds with:

`{"jsonrpc":"2.0","id":1,"error":{"code":-32602,"message":"Dash JSON-RPC: Request Error: getaddrinfo ENOTFOUND core"}}`

The node responds via ssl.

Changes need to be made to [improve error handling](https://discordapp.com/channels/670271785974890526/713693491322159106/785952216207851570) and to run `obtain` [without super-user privileges](https://discordapp.com/channels/670271785974890526/713693491322159106/786051891208650762).

**Comment by strophy** [comment]
Thanks for the comments! I have replaced `http-server` and `execa` with the same nginx docker image we use later for platform, since docker can bind port 80 without any problems. This means it is no longer necessary to install `http-server` globally (or at all) and superuser permissions are no longer necessary.

But after 5+ hours of trying, I cannot figure out how to wait for a function that returns a stream (`docker.pull('nginx')`) instead of a promise to complete. I've tried observables, callback functions, wrapping it in async functions... Any help [here](https://github.com/dashevo/mn-bootstrap/pull/196/commits/56940ba5e3338468c488f75fc5b0f086559a93be#diff-ed8a9e7b590618aeb9aa0118f7916da2b1ac7a8460d3dc4ed421262a6ad0a52cR61-R75) would be greatly appreciated!

**Comment by strophy** [comment]
I will pick this PR up again once #200 is merged so I am able to use the `dockerPull()` function it contains.

**Comment by riongull** [comment]
> I will pick this PR up again once #200 is merged so I am able to use the `dockerPull()` function it contains.

Any update on this?  Looks like #200 is merged now.

**Pull request closed without merging**
