### PR TITLE
feat: NPM cache for DAPI and Drive builds

### PR DESCRIPTION
**Pull request by shumkov**
## Issue being fixed or feature implemented

To speed up repeated Drive and DAPI docker image builds, npm cache generated on `node_modules` build stage should be copied back to NPM cache directory.

## What was done?

- Moved Drive and DAPI build paths to config (`platform.dapi.api.docker.build.path` and `platform.drive.abci.docker.build.path`)
- Made the `platform` option optional. The `compose.file` option removed, since `COMPOSE_FILE` generated automatically based on presents of `paltform` and `...docker.build.path` options.
- Singaled Docker Compose to use `docker build` command with BuildKit
- Moved templates to subdirectories
- Do not render platform templates for configs with the absent `platform` option
- Updated BLS library to solve sig falt that happens sometimes.

## How Has This Been Tested?

Running setup command

## Breaking Changes

- `dapi-image-build-path` and `drive-image-build-path` options moved to configs under `platform.dapi.api.docker.build.path` and `platform.drive.abci.docker.build.path` respectivly.

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated relevant unit/integration/functional/e2e tests
- [x] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [x] I have assigned this pull request to a milestone

### CODE REVIEW

**Comment by strophy** [comment]
How should I try to test this, in CI or local? What are the steps, what should I look for? I can't really understand the code changes, so not sure if my review is much help.

**Comment by shumkov** [comment]
With our new shiny GitHub actions

**Comment by strophy** [comment]
OK, here are some tests using this branch in CI:
using [buildkit](https://github.com/strophy/dapi/runs/2137087639?check_suite_focus=true): Fails with docker-compose error, both when pre-building and building only in docker-compose:
```
[FAILED] [10892] Failed to execute script docker-compose
[FAILED] Traceback (most recent call last):
[FAILED]   File "docker-compose", line 3, in <module>
[FAILED]   File "compose/cli/main.py", line 80, in main
[FAILED]   File "compose/cli/main.py", line 192, in perform_command
[FAILED]   File "compose/metrics/decorator.py", line 18, in wrapper
[FAILED]   File "compose/cli/main.py", line 369, in build
[FAILED]   File "compose/project.py", line 519, in build
[FAILED]   File "compose/project.py", line 501, in build_service
[FAILED]   File "compose/service.py", line 1131, in build
[FAILED]   File "compose/progress_stream.py", line 22, in stream_output
[FAILED]   File "compose/utils.py", line 50, in split_buffer
[FAILED]   File "compose/utils.py", line 26, in stream_as_text
[FAILED]   File "compose/service.py", line 1903, in build
[FAILED] IndexError: list index out of range
[FAILED] 
[FAILED] Docker Compose error: Building drive_abci
[FAILED] time="2021-03-18T05:50:15Z" level=warning msg="No output specified for docker-container driver. Build result will only remain in the build cache. To push result image into registry use --push or to load image into docker use --load"
```
using [docker native build:](https://github.com/strophy/dapi/runs/2144277533?check_suite_focus=true) Fails with blsjs.js error, both when pre-building and building only in docker-compose::
```
/home/runner/work/_actions/dashevo/gh-action-start-local-network/v0.1.17/tmp/mn-bootstrap/node_modules/bls-signatures/blsjs.js:6
var Module=typeof Module!=="undefined"?Module:{};var moduleOverrides={};var key;for(key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}Module["arguments"]=[];Module["thisProgram"]="./this.program";Module["quit"]=(function(status,toThrow){throw toThrow});Module["preRun"]=[];Module["postRun"]=[];var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;...[truncated]
```

**Comment by strophy** [comment]
The `platform` option needs to be set for non-local networks now as well, otherwise `mn reset --platform-only` fails with `Error: Cannot reset platform only if platform services are not enabled in config`. Issue #312

**Review by antouhou — APPROVED** [review]
👍

**Pull request merged**
